/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client1;

import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import MasterServer1.MasterServer1Interface;
import MasterServer2.MasterServer2Interface;
import bankingsystem.BankClient;
import Client1.Withdraw;
import java.util.ArrayList;

/**
 *
 * @author USER
 */
public class Client1GUI extends javax.swing.JFrame {

    BankClient bc = new BankClient();
    String area = "";
    Registry reg;
    boolean signedIn = false;
    Withdraw w;
    Deposit d;
    CheckBalance cb;

    /**
     * Creates new form Client1GUI
     */
    public Client1GUI() {
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);
        AreaComboBox.addItem("Sherouk");
        AreaComboBox.addItem("Nasr City");
        AreaComboBox.addItem("Dokki");
        AreaComboBox.addItem("Tagamoa");
        AreaComboBox.addItem("Zamalek");
        AreaComboBox.addItem("Obour");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaComboBox = new javax.swing.JComboBox<>();
        chooseAreaLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        NameBox = new javax.swing.JTextField();
        signInButton = new javax.swing.JButton();
        WithdrawButton = new javax.swing.JButton();
        DepositButton = new javax.swing.JButton();
        CheckBalanceButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AreaComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AreaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaComboBoxActionPerformed(evt);
            }
        });

        chooseAreaLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        chooseAreaLabel.setText("Area :");

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nameLabel.setText("Name :");

        NameBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        signInButton.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        signInButton.setText("Sign In");
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });

        WithdrawButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        WithdrawButton.setText("Withdraw");
        WithdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawButtonActionPerformed(evt);
            }
        });

        DepositButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DepositButton.setText("Deposit");
        DepositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositButtonActionPerformed(evt);
            }
        });

        CheckBalanceButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CheckBalanceButton.setText("Check Balance");
        CheckBalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBalanceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(chooseAreaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AreaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(signInButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(WithdrawButton)
                                .addGap(36, 36, 36)
                                .addComponent(DepositButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(CheckBalanceButton)))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(NameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseAreaLabel)
                    .addComponent(AreaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(signInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WithdrawButton)
                    .addComponent(DepositButton)
                    .addComponent(CheckBalanceButton))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AreaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaComboBoxActionPerformed
    }//GEN-LAST:event_AreaComboBoxActionPerformed

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed

        NameBox.setEditable(false);
        bc.setName(NameBox.getText());
        this.setTitle(NameBox.getText());
        area = (String) AreaComboBox.getSelectedItem();
        AreaComboBox.setEditable(false);
        try {
            w = new Withdraw(bc, area);
            d = new Deposit(bc, area);
            cb = new CheckBalance(bc);
        } catch (CloneNotSupportedException ex) {
            Logger.getLogger(Client1GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (area.equals("Sherouk") || area.equals("Obour") || area.equals("Tagamoa")) {
            try {
                reg = LocateRegistry.getRegistry("localhost", 1111);

                MasterServer1Interface obj = (MasterServer1Interface) reg.lookup("MASTER1");
                obj.signIn(bc,area);
            } catch (Exception ex) {
                Logger.getLogger(Client1GUI.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            try {
                reg = LocateRegistry.getRegistry("localhost", 2222);
                MasterServer2Interface obj = (MasterServer2Interface) reg.lookup("MASTER2");
                obj.signIn(bc, area);
            } catch (Exception ex) {
                Logger.getLogger(Client1GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        signedIn = true;
    }//GEN-LAST:event_signInButtonActionPerformed

    private void WithdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawButtonActionPerformed

        w.setVisible(true);
    }//GEN-LAST:event_WithdrawButtonActionPerformed

    private void DepositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositButtonActionPerformed
        d.setVisible(true);
    }//GEN-LAST:event_DepositButtonActionPerformed

    private void CheckBalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBalanceButtonActionPerformed
        cb.setVisible(true);
        if (area.equals("Sherouk") || area.equals("Obour") || area.equals("Tagamoa")) {
            try {
                reg = LocateRegistry.getRegistry("localhost", 1111);

                MasterServer1Interface obj = (MasterServer1Interface) reg.lookup("MASTER1");
                cb.updateBalanceBox(obj.callCheckBalance(bc, area));
            } catch (Exception ex) {
                Logger.getLogger(Client1GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                reg = LocateRegistry.getRegistry("localhost", 2222);

                MasterServer2Interface obj = (MasterServer2Interface) reg.lookup("MASTER2");
                cb.updateBalanceBox(obj.callCheckBalance(bc, area));
            } catch (Exception ex) {
                Logger.getLogger(Client1GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_CheckBalanceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client1GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AreaComboBox;
    private javax.swing.JButton CheckBalanceButton;
    private javax.swing.JButton DepositButton;
    private javax.swing.JTextField NameBox;
    private javax.swing.JButton WithdrawButton;
    private javax.swing.JLabel chooseAreaLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton signInButton;
    // End of variables declaration//GEN-END:variables
}
