/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client1;

import MasterServer1.MasterServer1Interface;
import MasterServer2.MasterServer2Interface;
import bankingsystem.BankClient;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Withdraw extends javax.swing.JFrame {

    BankClient bc = new BankClient();
    String area = "";

    public Withdraw() {
        initComponents();
    }

    public Withdraw(BankClient c, String area) throws CloneNotSupportedException {
        bc = (BankClient) c.clone();
        initComponents();
        this.setTitle(bc.getName());
        this.setResizable(false);
        this.area = area;
        setLocationRelativeTo(null);
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        withdrawLabel = new javax.swing.JLabel();
        AmountLabel = new javax.swing.JLabel();
        amountBox = new javax.swing.JTextField();
        confirmWithdrawButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        withdrawLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        withdrawLabel.setText("Withdraw");

        AmountLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AmountLabel.setText("Amount");

        amountBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        amountBox.setText("ex. 4000");
        amountBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountBoxActionPerformed(evt);
            }
        });

        confirmWithdrawButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmWithdrawButton.setText("Confirm");
        confirmWithdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmWithdrawButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(confirmWithdrawButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AmountLabel)
                                .addGap(39, 39, 39)
                                .addComponent(amountBox, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(withdrawLabel)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(withdrawLabel)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmountLabel)
                    .addComponent(amountBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(confirmWithdrawButton)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountBoxActionPerformed

    private void confirmWithdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmWithdrawButtonActionPerformed
        String amountStr = amountBox.getText();
        if (amountStr.matches("[0-9]+")) {
            double amount = Double.parseDouble(amountStr);
            if (amount < bc.getBalance()) {
                //Establish Connection and call withdraw function
                if (area.equals("Sherouk") || area.equals("Obour") || area.equals("Tagamoa")) {
                    try {
                        Registry reg = LocateRegistry.getRegistry("localhost", 1111);
                        MasterServer1Interface obj = (MasterServer1Interface) reg.lookup("MASTER1");
                        obj.callWithdraw(bc, amount, area);
                    } catch (Exception e) {
                        System.out.println("Error");
                    }
                    this.dispose();
                } else {
                    try {
                        Registry reg = LocateRegistry.getRegistry("localhost", 2222);
                        MasterServer2Interface obj = (MasterServer2Interface) reg.lookup("MASTER2");
                        obj.callWithdraw(bc, amount, area);
                    } catch (Exception e) {
                        System.out.println("Error");
                    }
                    this.dispose();
                }

            } else {
                JOptionPane.showMessageDialog(this, "You do not have enough balance", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Please Enter Numbers Only", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_confirmWithdrawButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Withdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountLabel;
    private javax.swing.JTextField amountBox;
    private javax.swing.JButton confirmWithdrawButton;
    private javax.swing.JLabel withdrawLabel;
    // End of variables declaration//GEN-END:variables
}
